### ISSUE TITLE
Erros de Conexão Intermitentes

### ISSUE THREAD

**Issue by uallasleles** [uallasleles/TRECIS#18]
Resolver falhas esporádicas ao iniciar serviço de envio para a API.

`RemoteDisconnected('Remote end closed connection without response',)`

**Comment by uallasleles** [comment]
```shell
Traceback (most recent call last):
  File "/send2api.py", line 67, in send
    headers=headers
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
```
